### ISSUE TITLE
Error when running asXML() method

### ISSUE THREAD

**Issue by pgjensen** [alberanid/imdbpy#107]
#### Issue description

Exception occurs when trying to export to XML (asXML()) with Python3

#### Version of IMDbPY, Python and OS

- **Python:** 3.5.2
- **IMDbPY:** 6.2 and 6.3-20171227 dev build
- **OS:** Ubuntu 16.04.3 updated

#### Steps to reproduce the issue

copy/pasta the main code example from https://github.com/alberanid/imdbpy page then add print(the_matrix.asXML()) at the end

```
#!python
# create and instance of the IMDb class
from imdb import IMDb
ia = IMDb()

# get a movie and print its director(s)
the_matrix = ia.get_movie('0133093')
#print(the_matrix['director'])
print(the_matrix.summary())
ia.update(the_matrix)
print(the_matrix.summary())
# show all the information sets avaiable for Movie objects
print(ia.get_movie_infoset())

# update a Movie object with more information
ia.update(the_matrix, ['technical'])
# show which keys were added by the information set
print(the_matrix.infoset2keys['technical'])
# print one of the new keys
print(the_matrix.get('cinematographic process'))

# search for a person
for person in ia.search_person('Mel Gibson'):
    print(person.personID, person['name'])

# get the first result of a company search,
# update it to get the basic information
ladd_company = ia.search_company('The Ladd Company')[0]
ia.update(ladd_company)
# show the available information and print some
print(ladd_company.keys())
print(ladd_company.get('production companies'))

# get 5 movies tagged with a keyword
dystopia = ia.get_keyword('dystopia', results=5)

# get a Character object
#deckard = ia.search_character('Rick Deckard')[0]
#ia.update(deckard)
#print(deckard['full-size headshot'])

# get top250 and bottom100 movies
top250 = ia.get_top250_movies()
bottom100 = ia.get_bottom100_movies()

print(the_matrix.asXML())
# your code here
```

#### What's the expected result?

- XML output to console

#### What's the actual result?

```
Movie
=====
Title: leading information resource for the entertainment industry, The (None)
Plot: Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the humans' body heat and electrochemical energy and who imprison their minds within an artificial reality known as the Matrix. As a rebel against the machines, Neo must return to the Matrix and confront the agents: super-powerful computer programs devoted to snuffing out Neo and the entire human rebellion.
Movie
=====
Title: leading information resource for the entertainment industry, The (None)
Plot: Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the humans' body heat and electrochemical energy and who imprison their minds within an artificial reality known as the Matrix. As a rebel against the machines, Neo must return to the Matrix and confront the agents: super-powerful computer programs devoted to snuffing out Neo and the entire human rebellion.
['airing', 'akas', 'alternate versions', 'awards', 'business', 'connections', 'crazy credits', 'critic reviews', 'episodes', 'episodes cast', 'episodes rating', 'external reviews', 'faqs', 'full credits', 'goofs', 'guests', 'keywords', 'literature', 'locations', 'main', 'misc sites', 'news', 'official sites', 'parents guide', 'photo sites', 'plot', 'quotes', 'recommendations', 'release dates', 'release info', 'sound clips', 'soundtrack', 'synopsis', 'taglines', 'technical', 'trivia', 'tv schedule', 'video clips', 'vote details']
['aspect ratio', 'runtime', 'camera', 'negative format', 'cinematographic process', 'laboratory', 'color', 'sound mix', 'printed film format']
['Digital Intermediate (remastered version)', 'Super 35', 'VistaVision (effects shots)']
0000154 Mel Gibson
2153167 Mel Gibson
0317112 Mel Gibson
3323885 Adam Taylor
2800055 Mel Gibson
6709224 Mel Gibson
0317195 Terel Gibson
0316945 Donal Gibson
2106809 Raquel Gibson
0316878 Cal Gibson
7133936 Jamel Gibson
7699405 Jamel Gibson
3912400 Jamel Gibson
0316950 E.L. Gibson
4047961 Noel Gibson
9235742 Daniel Gibson
1270944 Paul Gibson
2988370 Mal Gibson
2798174 Daniel Gibson
7454542 L. Gibson
['name', 'long imdb name']
None
Traceback (most recent call last):
  File "imdb_test.py", line 45, in <module>
    print(the_matrix.asXML())
  File "/usr/local/lib/python3.5/dist-packages/imdb/utils.py", line 1456, in asXML
    beginTag, endTag = _tag4TON(self, addAccessSystem=True, _containerOnly=True)
  File "/usr/local/lib/python3.5/dist-packages/imdb/utils.py", line 953, in _tag4TON
    value = _normalizeValue(value)
  File "/usr/local/lib/python3.5/dist-packages/imdb/utils.py", line 931, in _normalizeValue
    value = _handleTextNotes(escape4xml(value))
  File "/usr/local/lib/python3.5/dist-packages/imdb/utils.py", line 919, in _handleTextNotes
    ssplit = s.split('::', 1)
TypeError: a bytes-like object is required, not 'str'
```

#### Additional details

- Is this related to the current parsing issues from the website somehow?

**Comment by alberanid** [comment]
@pgjensen thanks for the report.  I don't think it's related to the other problems; there should be something wrong with the unicode/string handling.
