### ISSUE TITLE
Crash on get_movies

### ISSUE THREAD

**Issue by slef** [alberanid/imdbpy#139]
#### Issue description
With Python 3.6.4, on MacOS, imdbpy crashes on any get_movie

```
>>> import imdb
>>> i = imdb.IMDb()
>>> m = i.get_movie('0133093')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/imdb/parser/http/utils.py", line 453, in parse
    self.gather_refs(dom)
  File "/usr/local/lib/python3.6/site-packages/imdb/parser/http/utils.py", line 536, in gather_refs
    refs = grParser.parse_dom(dom)
AttributeError: 'GatherRefs' object has no attribute 'parse_dom'
[...]
```

#### Version of IMDbPY, Python and OS

- **Python:** 3.6.4
- **IMDbPY:** 6.5dev20180316
- **OS:** `uname_result(system='Darwin', node='Stefans-MacBook-Air.local', release='17.5.0', version='Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64', machine='x86_64', processor='i386')`

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python

import imdb
i = imdb.IMDb()
m = i.get_movie('0133093')
```

#### What's the expected result?

- Put the Matrix movie in m

#### What's the actual result?

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/imdb/parser/http/utils.py", line 453, in parse
    self.gather_refs(dom)
  File "/usr/local/lib/python3.6/site-packages/imdb/parser/http/utils.py", line 536, in gather_refs
    refs = grParser.parse_dom(dom)
AttributeError: 'GatherRefs' object has no attribute 'parse_dom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "imdbtest.py", line 3, in <module>
    m = i.get_movie('0133093')
  File "/usr/local/lib/python3.6/site-packages/imdb/__init__.py", line 401, in get_movie
    self.update(movie, info)
  File "/usr/local/lib/python3.6/site-packages/imdb/__init__.py", line 709, in update
    ret = method(mopID)
  File "/usr/local/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 427, in get_movie_plot
    ret = self.mProxy.plot_parser.parse(cont, getRefs=self._getRefs)
  File "/usr/local/lib/python3.6/site-packages/imdb/parser/http/utils.py", line 456, in parse
    self._cname, exc_info=True)
Message: '%s: unable to gather refs: %s'
Arguments: ('DOMHTMLPlotParser',)
```

**Comment by uyar** [comment]
This should be fixed, thanks for reporting it.

**Comment by slef** [comment]
Yes it works now! Thanks!
