### ISSUE TITLE
getting this weird error

### ISSUE THREAD

**Issue by dannybwee** [alberanid/imdbpy#163]
INFO:root:begin processing file /Users/danielbui/Downloads/title.principals.tsv.gz
/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:508: Warning: 'utf8' is currently an alias for the character set UTF8MB3, which will be replaced by UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
cursor.execute(statement, parameters)

INFO:root:end processing file /Users/danielbui/Downloads/title.principals.tsv.gz: 28647546 entries
INFO:root:begin processing file /Users/danielbui/Downloads/title.akas.tsv.gz
Traceback (most recent call last):
File "/usr/local/bin/s32imdbpy.py", line 177, in 
import_dir(dir_name, engine)
File "/usr/local/bin/s32imdbpy.py", line 162, in import_dir
import_file(fn, engine)
File "/usr/local/bin/s32imdbpy.py", line 136, in import_file
metadata.create_all(tables=[table])
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
tables=tables)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
conn._run_visitor(visitorcallable, element, **kwargs)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
**kwargs).traverse_single(element)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
_is_metadata_operation=True)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 796, in visit_table
self.traverse_single(index)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 823, in visit_index
self.connection.execute(CreateIndex(index))
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
return connection._execute_ddl(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
compiled
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
exc_info
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
cursor.execute(statement, parameters)
File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
self.errorhandler(self, exc, value)
File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
raise errorclass, errorvalue
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'title' used in key specification without a key length") [SQL: u'CREATE INDEX ix_title_akas_title ON title_akas (title)'] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by dannybwee** [comment]
getting this error when running the s32imdbpy.py script

**Comment by alberanid** [comment]
@dannybwee : please try using Python 3.  Python 2.7 support is mostly untested.

**Comment by ChakshuGautam** [comment]
Getting this in python 3.5

**Comment by alberanid** [comment]
thanks for the report; it should be fixed in the repository version.

**Comment by alberanid** [comment]
Please notice that for some database engines (like MySQL and MariaDB) you may need to specify the charset on the URI and sometimes also the dialect, with something like 'mysql+mysqldb://username:password@localhost/imdb?charset=utf8'
