### ISSUE TITLE
searchMovieAdvancedParser throws an exception for certain movie titles

### ISSUE THREAD

**Issue by hjwidmaier** [alberanid/imdbpy#314]
#### Issue description

For certain movie searches parsing the info data results in an exception as there is no match:

#### Version of IMDbPY, Python and OS

Python 3.9.3, IMDbPY 2021.04.18, Arch Linux 5.11.15-arch1-2

#### Steps to reproduce the issue

```
#!/usr/bin/env python

from imdb import IMDb

ia = IMDb()

sprint(len(ia.search_movie_advanced("Othello")))
```

#### What's the expected result?

20

#### What's the actual result?

```
2021-04-18 19:12:38,269 ERROR [imdbpy.parser.http.domparser] /home/hjw/sw/imdbpy/imdb/parser/http/utils.py:440: DOMHTMLSearchMovieAdvancedParser: caught exception postprocessing data
Traceback (most recent call last):
  File "/home/hjw/sw/imdbpy/imdb/parser/http/utils.py", line 438, in parse
    data = self.postprocess_data(data)
  File "/home/hjw/sw/imdbpy/imdb/parser/http/searchMovieAdvancedParser.py", line 236, in postprocess_data
    secondary = _parse_secondary_info(secondary_info)
  File "/home/hjw/sw/imdbpy/imdb/parser/http/searchMovieAdvancedParser.py", line 56, in _parse_secondary_info
    if match.group(2):
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/surfer/data/sw/jfs/jfs/./badinfo.py", line 8, in <module>
    movie = ia.search_movie_advanced("Othello")
  File "/home/hjw/sw/imdbpy/imdb/__init__.py", line 474, in search_movie_advanced
    return [Movie.Movie(movieID=self._get_real_movieID(mi),
  File "/home/hjw/sw/imdbpy/imdb/__init__.py", line 476, in <listcomp>
    accessSystem=self.accessSystem) for mi, md in res][:results]
ValueError: too many values to unpack (expected 2)
```

#### Additional details

I've worked around this by checking if a match object was actually returned. If not, I just return the parenthesied value as 'kind'.
This is certainly not the  correct way to handle it, but I don't like exceptions in libraries I can't handle.

My kludge:

```
def _parse_secondary_info(info):
    parsed = {}
    match = _re_secondary_info.match(info)
    kind = None
    if not match:
        parsed["kind"] = info[1:-1]
        return parsed

    if match.group(2):
    [...]

```

**Comment by alberanid** [comment]
This issue is no longer relevant due to issue #557: ss of June 2026, Cinemagoer no longer analyzes web pages and can only rely on non-commercial datasets.
