### ISSUE TITLE
Help with a Telegram bot...

### ISSUE THREAD

**Issue by VasuDevbyte** [alberanid/imdbpy#322]
#### Issue description

First thing First IAM working on a Telegram auto filter Movie bot!! 
So People are Always doing Spelling Mistake so To overcome that I tried this using this...!

#### Steps to reproduce the issue
These are My Heroku Error logs..!
`2021-07-05T02:19:44.359665+00:00 app[worker.1]:     r = await self.session.send(
2021-07-05T02:19:44.359665+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/session.py", line 425, in send
2021-07-05T02:19:44.359666+00:00 app[worker.1]:     return await self._send(data, timeout=timeout)
2021-07-05T02:19:44.359666+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/session.py", line 395, in _send
2021-07-05T02:19:44.359667+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2021-07-05T02:19:44.359667+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
2021-07-05T02:19:44.359667+00:00 app[worker.1]:     raise getattr(
2021-07-05T02:19:44.359669+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: [400 BUTTON_URL_INVALID]: The button url is invalid (caused by "messages.SendMessage")
2021-07-05T02:19:49.791115+00:00 app[worker.1]: 2021-07-05 02:19:49,790 INFO [imdbpy.parser.http.piculet] /app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/piculet.py:681: using lxml html builder
2021-07-05T02:19:49.791515+00:00 app[worker.1]: [05-Jul-21 02:19:49 - INFO] - imdbpy.parser.http.piculet - using lxml html builder
2021-07-05T02:25:16.388259+00:00 app[worker.1]: 2021-07-05 02:25:16,388 INFO [imdbpy.parser.http.piculet] /app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/piculet.py:681: using lxml html builder
2021-07-05T02:25:16.388772+00:00 app[worker.1]: [05-Jul-21 02:25:16 - INFO] - imdbpy.parser.http.piculet - using lxml html builder
2021-07-05T02:25:17.117368+00:00 app[worker.1]: [05-Jul-21 02:25:17 - WARNING] - pyrogram.parser.html - Unclosed tags: <code> (x2)
2021-07-05T02:26:01.277976+00:00 app[worker.1]: 2021-07-05 02:26:01,277 INFO [imdbpy.parser.http.piculet] /app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/piculet.py:681: using lxml html builder
2021-07-05T02:26:01.278139+00:00 app[worker.1]: [05-Jul-21 02:26:01 - INFO] - imdbpy.parser.http.piculet - using lxml html builder
2021-07-05T02:26:02.406066+00:00 app[worker.1]: [05-Jul-21 02:26:02 - ERROR] - pyrogram.dispatcher - [400 BUTTON_URL_INVALID]: The button url is invalid (caused by "messages.SendMessage")
2021-07-05T02:26:02.406083+00:00 app[worker.1]: Traceback (most recent call last):
2021-07-05T02:26:02.406084+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-07-05T02:26:02.406085+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-07-05T02:26:02.406085+00:00 app[worker.1]:   File "/app/bot/plugins/auto_filter.py", line 133, in auto_filter
2021-07-05T02:26:02.406086+00:00 app[worker.1]:     send_msg = await bot.send_message(
2021-07-05T02:26:02.406086+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/messages/send_message.py", line 125, in send_message
2021-07-05T02:26:02.406087+00:00 app[worker.1]:     r = await self.send(
2021-07-05T02:26:02.406088+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
2021-07-05T02:26:02.406088+00:00 app[worker.1]:     r = await self.session.send(
2021-07-05T02:26:02.406088+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/session.py", line 425, in send
2021-07-05T02:26:02.406089+00:00 app[worker.1]:     return await self._send(data, timeout=timeout)
2021-07-05T02:26:02.406090+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/session/session.py", line 395, in _send
2021-07-05T02:26:02.406090+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2021-07-05T02:26:02.406091+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
2021-07-05T02:26:02.406091+00:00 app[worker.1]:     raise getattr(
2021-07-05T02:26:02.406092+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: [400 BUTTON_URL_INVALID]: The button url is invalid (caused by "messages.SendMessage")
2021-07-05T02:26:29.912504+00:00 app[worker.1]: 2021-07-05 02:26:29,912 INFO [imdbpy.parser.http.piculet] /app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/piculet.py:681: using lxml html builder
2021-07-05T02:26:29.912670+00:00 app[worker.1]: [05-Jul-21 02:26:29 - INFO] - imdbpy.parser.http.piculet - using lxml html builder
2021-07-05T02:26:30.728493+00:00 app[worker.1]: [05-Jul-21 02:26:30 - WARNING] - pyrogram.parser.html - Unclosed tags: <code> (x2)
2021-07-05T02:26:36.249722+00:00 app[worker.1]: 2021-07-05 02:26:36,249 INFO [imdbpy.parser.http.piculet] /app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/piculet.py:681: using lxml html builder
2021-07-05T02:26:36.249888+00:00 app[worker.1]: [05-Jul-21 02:26:36 - INFO] - imdbpy.parser.http.piculet - using lxml html builder
2021-07-05T02:26:58.549430+00:00 app[worker.1]: 2021-07-05 02:26:58,549 INFO [imdbpy.parser.http.piculet] /app/.heroku/python/lib/python3.9/site-packages/imdb/parser/http/piculet.py:681: using lxml html builder
2021-07-05T02:26:58.549532+00:00 app[worker.1]: [05-Jul-21 02:26:58 - INFO] - imdbpy.parser.http.piculet - using lxml html builder`

#!python

# your code here
my code...
[My Code Goes like here..!](https://github.com/VasuDevbyte/Adv-Auto-Filter-Bot-V2/blob/aeadb89612f673e61b77cfdd8856d0a886fdc8cb/bot/plugins/auto_filter.py#L24) [Trying to send a Crct spelling..](https://github.com/VasuDevbyte/Adv-Auto-Filter-Bot-V2/blob/aeadb89612f673e61b77cfdd8856d0a886fdc8cb/bot/plugins/auto_filter.py#L135) 

#### What's the expected result?

-Hey I've think you made spelling mistake
Try Thiz :- {Sea_rch} used it as a variable

#### What's the actual result?
But results gone wrong🥲
-
![Screenshot_20210705_075532](https://user-images.githubusercontent.com/81460710/124410385-f2371c00-dd67-11eb-98c6-6211b55f3be4.jpg)

#### Additional details

Iam new to python...
Just Tryed something...

**Comment by alberanid** [comment]
Hi, sorry but I can't be of any help on this.

I'm pretty sure the problem is that the Telegram library is not escaping your text correctly, and the Telegram clients on the phones will replace some strings with emoji.

You need to find out how to sanitize and escape "special chars" on your strings.
