### ISSUE TITLE
Install without sql feature fails

### ISSUE THREAD

**Issue by Kraymer** [alberanid/imdbpy#33]
repo freshly cloned,
OSX 10.11.12

```
flap at MacBook-Pro on master* ± python ./setup.py --without-sql  install                                                                                          ~/Dev/imdbpy 1 ↵ 
Created locale for: ar bg de en es fr it tr.
Traceback (most recent call last):
  File "./setup.py", line 238, in <module>
    setuptools.setup(**params)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "build/bdist.macosx-10.9-x86_64/egg/setuptools/dist.py", line 275, in parse_command_line
  File "build/bdist.macosx-10.9-x86_64/egg/setuptools/dist.py", line 371, in _finalize_features
  File "build/bdist.macosx-10.9-x86_64/egg/setuptools/dist.py", line 785, in include_in
  File "build/bdist.macosx-10.9-x86_64/egg/setuptools/dist.py", line 414, in include_feature
distutils.errors.DistutilsOptionError: access to SQL databases is required, but was excluded or is not available
```

**Comment by alberanid** [comment]
Hi,
it seems that some of the logic behind setuptools has changed.

You can obtain the same result specifying also the --without-sqlobject --without-sqlalchemy command line arguments.

Thanks for the report!
