### ISSUE TITLE
Exception not being caught

### ISSUE THREAD

**Issue by Gabriel-p** [alberanid/imdbpy#333]
#### Issue description

Using a wrong ID results in a cascade of errors that can not be caught (as described [here](https://imdbpy.readthedocs.io/en/latest/usage/quickstart.html?highlight=exception#exceptions)).

#### Version of IMDbPY, Python and OS

> Python 3.9.6
> 2021.04.18
> uname_result(system='Linux', node='gabriel-desk', release='5.5.0-050500-generic', version='#202001262030 SMP Mon Jan 27 01:33:36 UTC 2020', machine='x86_64')

**NOTICE: please always try the latest version from the repository before submitting a bug.**

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
- **IMDbPY:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`
- **OS:** `python -c 'import platform ; print(platform.uname())'`

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```python
#!/usr/bin/env python

from imdb import IMDb, IMDbError

ia = IMDb()
try:
    movie = ia.get_movie("76576567")
except IMDbError:
    print("catched")
```

#### What's the expected result?

Error should be caught

#### What's the actual result?

It is not

#### Additional details

-

**Comment by alberanid** [comment]
From a quick test, it does catch the exception since the changes introduced in #238 ; however being a little too verbose the intermediate exceptions are printed anyway (but the execution flow continues):
```
$ ~/test.py 
2021-09-08 22:47:24,275 CRITICAL [imdbpy] /home/da/git/imdbpy/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt76576567/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 404: ''>},); kwds: {}
Traceback (most recent call last):
  File "/home/da/git/imdbpy/imdb/parser/http/__init__.py", line 221, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 
2021-09-08 22:47:24,277 CRITICAL [imdbpy] /home/da/git/imdbpy/imdb/__init__.py:789: caught an exception retrieving or parsing "main" info set for mopID "76576567" (accessSystem: http)
Traceback (most recent call last):
  File "/home/da/git/imdbpy/imdb/parser/http/__init__.py", line 221, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/da/git/imdbpy/imdb/__init__.py", line 787, in update
    ret = method(mopID)
  File "/home/da/git/imdbpy/imdb/parser/http/__init__.py", line 464, in get_movie_main
    cont = self._retrieve(self.urls['movie_main'] % movieID + 'reference')
  File "/home/da/git/imdbpy/imdb/parser/http/__init__.py", line 379, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
  File "/home/da/git/imdbpy/imdb/parser/http/__init__.py", line 249, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt76576567/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 404: ''>}
catched
```

As you can see, it also prints "catched".

In any case, I agree that:
* we should be less verbose (maybe we can introduce a `verbose` parameter?)
* in general the handling of imdbID should be a little more smart and support both integers and strings

**Comment by Gabriel-p** [comment]
You are correct, it does catch it. Closing
