### ISSUE TITLE
Exception fetching episodes list of series with no episodes

### ISSUE THREAD

**Issue by alberanid** [alberanid/imdbpy#348]
Some series have no episodes listed, and this will cause an exception:

```python
>>> series=ia.get_movie('13399872', info= 'main')
>>> series
<Movie id:13399872[http] title:_"Domicilio coatto" (2020)_>
>>> ia.update(series, info = 'episodes')
2021-09-22 13:42:10,039 CRITICAL [imdbpy] /home/guglielmo/anaconda3/envs/gender_imdb/lib/python3.8/site-packages/imdb/__init__.py:789: caught an exception retrieving or parsing "episodes" info set for mopID "13399872" (accessSystem: http)
Traceback (most recent call last):
  File "/home/guglielmo/anaconda3/envs/gender_imdb/lib/python3.8/site-packages/imdb/__init__.py", line 787, in update
    ret = method(mopID)
  File "/home/guglielmo/anaconda3/envs/gender_imdb/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 653, in get_movie_episodes
    data_d['data']['number of episodes'] = nr_eps
KeyError: 'data'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guglielmo/anaconda3/envs/gender_imdb/lib/python3.8/site-packages/imdb/__init__.py", line 787, in update
    ret = method(mopID)
  File "/home/guglielmo/anaconda3/envs/gender_imdb/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 653, in get_movie_episodes
    data_d['data']['number of episodes'] = nr_eps
KeyError: 'data'
```

**Comment by Philippe-Cholet** [comment]
In that case, `data_d` is empty (because we don't reach the line 652: `data_d = other_d`).

Instead of line 653
```python
data_d['data']['number of episodes'] = nr_eps
```
Just test if it's not empty before assigning the number of episodes:
```python
if data_d:
    data_d['data']['number of episodes'] = nr_eps
```
Or if you want the result to be not empty:
```python
if not data_d:
    data_d['data'] = dict()
data_d['data']['number of episodes'] = nr_eps
```
