### ISSUE TITLE
'news' movie infoset not working

### ISSUE THREAD

**Issue by filipbacic** [alberanid/imdbpy#360]
#### Issue description

'news' movie infoset is reporting error

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```python
#!/usr/bin/env python

import imdb

i = imdb.IMDb()
movie_list = i.search_movie('superior donuts')
print(i.get_movie_infoset())
first_match = movie_list[0]
print(first_match.keys())
i.update(first_match, 'news')
print(first_match.keys())
```

#### What's the expected result?

To return list of keys.

#### What's the actual result?

['airing', 'akas', 'alternate versions', 'awards', 'connections', 'crazy credits', 'critic reviews', 'episodes', 'external reviews', 'external sites', 'faqs', 'full credits', 'goofs', 'keywords', 'list', 'locations', 'main', 'misc sites', 'news', 'official sites', 'parents guide', 'photo sites', 'plot', 'quotes', 'recommendations', 'release dates', 'release info', 'reviews', 'sound clips', 'soundtrack', 'synopsis', 'taglines', 'technical', 'trivia', 'tv schedule', 'video clips', 'vote details']
['title', 'kind', 'year', 'cover url', 'canonical title', 'long imdb title', 'long imdb canonical title', 'smart canonical title', 'smart long imdb canonical title', 'full-size cover url']
2021-11-21 22:29:26,720 CRITICAL [imdbpy] C:\ProgramData\Anaconda3\lib\site-packages\imdb\__init__.py:792: caught an exception retrieving or parsing "news" info set for mopID "5462364" (accessSystem: http)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\__init__.py", line 787, in update
    ret = method(mopID)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\__init__.py", line 604, in get_movie_news
    return self.mProxy.news_parser.parse(cont, getRefs=self._getRefs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\utils.py", line 434, in parse
    data = self.parse_dom(dom)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\utils.py", line 526, in parse_dom
    return Rules(self.rules).extract(dom)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\piculet.py", line 373, in extract
    value = self.apply(element)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\piculet.py", line 517, in apply
    extracted = rule.extract(subroot)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\piculet.py", line 589, in extract
    list(map(self.extractor.transform, values))
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\movieParser.py", line 2080, in <lambda>
    'date': x.get('fromdate').split('|')[0].strip(),
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "news_test.py", line 8, in <module>
    i.update(first_match, 'news')
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\__init__.py", line 787, in update
    ret = method(mopID)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\__init__.py", line 604, in get_movie_news
    return self.mProxy.news_parser.parse(cont, getRefs=self._getRefs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\utils.py", line 434, in parse
    data = self.parse_dom(dom)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\utils.py", line 526, in parse_dom
    return Rules(self.rules).extract(dom)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\piculet.py", line 373, in extract
    value = self.apply(element)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\piculet.py", line 517, in apply
    extracted = rule.extract(subroot)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\piculet.py", line 589, in extract
    list(map(self.extractor.transform, values))
  File "C:\ProgramData\Anaconda3\lib\site-packages\imdb\parser\http\movieParser.py", line 2080, in <lambda>
    'date': x.get('fromdate').split('|')[0].strip(),
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by alberanid** [comment]
This issue is no longer relevant due to issue #557: ss of June 2026, Cinemagoer no longer analyzes web pages and can only rely on non-commercial datasets.
